theme: minima
title: Hey you!
author: GitHub User Ich
email: karolina@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Hi everyone

# social links
twitter_username: n/a
github_username:  private

show_excerpts: true # set to false to remove excerpts on the homepage
